'use client'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider, createGlobalStyle } from "styled-components";
import { theme } from "./globals.css";


const GlobalStyle = createGlobalStyle`
* {
  box-sizing: border-box;
  padding: 0;
  margin: 0;
}

html,
body {
  max-width: 100vw;
  overflow-x: hidden;
};
main{
  position: absolute;
  top: 80px;
  width: 100%;
  background-color: ${(props) => props.theme.colors.gray};
}
`;

const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Eric Soares Dev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}><ThemeProvider theme={theme}><GlobalStyle/>{children}</ThemeProvider></body>
    </html>
  );
}
